"use strict";

//cryptocurrency api
const api_key1 ="960e428fdca399a09e41196327f5766b1f76aa979eec604f31318a4e0ac3f032";
//news api
const api_key2 = "3d4f6056ea124d38aff81d043310b2f2";

//formats parameters for urls
function formatQueryParams(params) {
    const queryItems = Object.keys(params)
        .map(key => `${encodeURIComponent(key)}=${encodeURIComponent(params[key])}`)
    return queryItems.join('&');
}

//canvas settings for background
window.onload = function () {
    Particles.init({
        selector: ".background",
        color: "#c6a307",
        connectParticles: true,
        maxParticles: 160,
        minDistance: 90,
        speed: 0.33
    });
};

//event for clicking "CryptOracle logo"
function reloadPage() {
    $(".logo").on("click", function () {
        location.reload();
    });

}

//event for clicking "Top 10 Coins"
function registerNavbtnI() {
    $(".nav-btn1").on("click",function(event){
        event.preventDefault();
        $(this).prop("disabled", true);
        $(".landing").empty();
        generateTopTenLayout();
        generateTopTen();
    })
}

//event for clicking "About"
function generateAbout() {
    $(".about-btn").on("click", function (event) {
        $(".landing").empty();
        $(".landing").append(`<div class="about-page">"Lorem ipsum dolor sit amet, consectetur adipiscing elit, 
        sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, 
        quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
        Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. 
        Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
        </div>
`);
    });
}

//generates html elements for generateTopTen() to append future li's
function generateTopTenLayout() {
    $(".landing").hide().fadeIn().append(`
        <section>
            <h2>Toplist by 24 Hour Volume Subscriptions</h2>
                <table class="top-currencies">
                    <tr class="main-table">
                        <th>Name</th>
                        <th>Price</th>
                        <th>High/Low</th>
                    </tr>
                </table>
        </section>`)
}

//fetch endpoint "Top 10 total volume" and append results to html elements generated by generateTopTenLayout()
function generateTopTen() {
    const searchUrl = "https://min-api.cryptocompare.com/data/top/totalvolfull";//correct base url?
    const baseImageUrl = "https://www.cryptocompare.com/";

    let params = {
        limit: "10",
        tsym: "USD",
        api_key: api_key1
    };

    const queryString = formatQueryParams(params);
    const url = searchUrl + "?" + queryString;

    return fetch(url)
        .then(function(response) {
            if (response.ok) {
                return response.json();
            } throw new Error(response.statusText);
        })
        .then(function (responseJson) {
            for( let i=0; i<responseJson.Data.length; i++) {
                $(".top-currencies").hide().fadeIn().append(`
                <tr class="table-info">
                    <td class="cName"><img class="icons" src="${baseImageUrl}${responseJson.Data[i].CoinInfo.ImageUrl}">${responseJson.Data[i].CoinInfo.FullName}</td>
                    <td class="price">${responseJson.Data[i].DISPLAY.USD.PRICE}</td>
                    <td class="volume">${responseJson.Data[i].DISPLAY.USD.HIGHDAY}/${responseJson.Data[i].DISPLAY.USD.LOWDAY}</td>
                </tr>
                `);
            }
      
        })
        .catch(error => console.log("generateTopTen failed"));
}
////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// landing page generates 3 most recent news articles for cryptocurrency 
// function generateNews(){
//     const searchUrl = "https://newsapi.org/v2/everything?q=cryptocurrency+blockchain&apiKey=";
//     const url = searchUrl + api_key2;
//     return fetch(url)
//         .then(response => {
//             if (response.ok){
//                 return response.json();
//             } throw new Error(response.statusText);
//         })

//         .then(function (responseJson){
//             for(let i=0; i<6;i++){
//                 $(".news-articles").append(`
//                     <article class="article"><a class="a-link" href="${responseJson.articles[i].url}"><span>${responseJson.articles[i].title}</span><span>${responseJson.articles[i].source.name}</span><img src="${responseJson.articles[i].urlToImage}"></a></article>
//                     `)}
//                 })
//         .catch(error => console.log("generateNews failed"))

// }
/////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////



//event for submitting a search on landing page
function registerEvents(){
    $(".search-bar").on("submit", function(event) {
        event.preventDefault();
        
        let searchTerm = (($(".search-term").val()).toUpperCase());
        console.log("search term", searchTerm);

        let searchMarket = $(".search-ex").val();
        console.log("market", searchMarket);

        let fCurrency = $(".search-xxx").val();
        console.log("fcurrecny", fCurrency);

        $(".landing").empty();

        generateResultsMedia(searchTerm);
        generateResults(searchTerm, searchMarket, fCurrency);

        
    })
}

//generates statistics from Custom Average endpoint
function generateResults(search, exchange, currency) {
    const searchUrl = "https://min-api.cryptocompare.com/data/generateAvg"
    if(exchange ==="") {
        exchange = "CCCAGG";
    }

    if(search==="") {
        search ="BTC";
    }

    let params = {
        fsym: search,
        tsym: currency,
        e: exchange,
        api_key: api_key1
    };

    const queryString = formatQueryParams(params);
    const url = searchUrl + "?" + queryString;

    return fetch(url)
        .then(function(response) {
            if (response.ok) {
                return response.json();
            } throw new Error(response.statusText);
        })

        .then(function (responseJson) {// seperate function?
            $(".landing").append(`<div class="checktest"></div>`);
            $(".checktest").append(`<div>Price: ${responseJson.DISPLAY.PRICE}</div><div>`)
            $(".checktest").append(`<div>Open24: ${responseJson.DISPLAY.OPEN24HOUR}</div>`)
            $(".checktest").append(`<div>High24: ${responseJson.DISPLAY.HIGH24HOUR}</div>`)
            $(".checktest").append(`<div>Low24: ${responseJson.DISPLAY.LOW24HOUR}</div>`)
            $(".checktest").append(`<div>Change24: ${responseJson.DISPLAY.CHANGE24HOUR}</div>`)
            $(".checktest").append(`<div>ChangePercent: ${responseJson.DISPLAY.CHANGEPCT24HOUR}%</div>`)
        })
        .catch(error => console.log("1 error happened"));
}

//generates name from seperate endpoint, only that endpoint contains fullname of search query
function generateResultsMedia(search) {
    const searchUrl = "https://min-api.cryptocompare.com/data/all/coinlist"

    const url = searchUrl + "?" + api_key1;

    if(search ==""){
        search = "BTC"
    }
    return fetch(url)
        .then(function(response) {
            if (response.ok) {
                return response.json();
            } throw new Error(response.statusText);
        })

        .then(function (responseJson) {
            console.log("123", responseJson.Data[search].FullName)
            $(".checktest").append(`<div>${responseJson.Data[search].FullName}</div>`);
            
        })
        .catch(error => console.log(error));
}

function documentReady() {
    // generateTopTenLayout();
    // generateTopTen();
    // generateNews();
    registerEvents();
    registerNavbtnI();
    generateAbout();
    reloadPage();
    // test();
}

$(documentReady);


















